class AgregaTejedores < ActiveRecord::Migration[5.2]
  def up
    if Cor1440Gen::Proyectofinanciero.where(id: 142).count == 0
        execute <<-SQL
          INSERT INTO cor1440_gen_proyectofinanciero (id, nombre, observaciones, fechainicio, fechacierre, responsable_id, fechacreacion, fechadeshabilitacion, created_at, updated_at, compromisos, monto) VALUES (142, 'U EUROPEA//2018-2020/TEJEDORES DE VIDA: una apuesta de educación para la paz y la reconciliación desde las nuevas generaciones. ', 'Euros', '2018-03-01', '2020-09-30', 27, NULL, NULL, '2018-02-20 19:52:46.855238', '2018-02-23 20:41:18.86084', '', 897425);
          
          SELECT setval('cor1440_gen_proyectofinanciero_id_seq', MAX(id)+1, true) FROM cor1440_gen_proyectofinanciero;
          
          
          INSERT INTO cor1440_gen_objetivopf (id, proyectofinanciero_id, numero, objetivo) VALUES (8, 142, 'OG', 'Contribuir a la consolidación de una cultura de paz en Colombia, desde una propuesta de educación transformadora a adolescentes, jóvenes y sus entornos educativos y comunitarios, que aporte a la reducción de brechas sociales y la promoción de ciudadanías creativas que aclimaten escenarios de reconciliación personal, comunitaria y socio-ecológica');
          INSERT INTO cor1440_gen_objetivopf (id, proyectofinanciero_id, numero, objetivo) VALUES (9, 142, 'OE', 'Potenciar habilidades y capacidades en adolescentes y jóvenes, sus entornos educativos y las comunidades de influencia de estos, en contextos urbano-rurales, para desnaturalizar la violencia, retejer relaciones justas entre sectores tradicionalmente distantes u opuestos y ejercer prácticas orientadas a la gobernanza ambiental de sus territorios, aportando así de forma creativa, a una cultura de paz consecuente con el desafío histórico de la reconciliación en Colombia');
          
          SELECT setval('cor1440_gen_objetivopf_id_seq', MAX(id)+1, true) FROM cor1440_gen_objetivopf;
          
          
          INSERT INTO cor1440_gen_resultadopf (id, proyectofinanciero_id, objetivopf_id, numero, resultado) VALUES (11, 142, 9, 'R.Z 0', 'Establecimiento de línea de base, sistema de monitoreo, seguimiento y fortalecimiento, compilación de herramientas y metodologías que contribuyan al aseguramiento de la calidad de la acción. ');
          INSERT INTO cor1440_gen_resultadopf (id, proyectofinanciero_id, objetivopf_id, numero, resultado) VALUES (12, 142, 9, 'Rz 1.1', '1536 Adolescentes, jóvenes y educadores en dieciséis colegios públicos y privados del país, han desarrollado habilidades para la transformación de conductas violentas y la mediación alternativa, dialogada y creativa de los conflictos, actuando como promotores de paz en sus colegios y comunidades.');
          INSERT INTO cor1440_gen_resultadopf (id, proyectofinanciero_id, objetivopf_id, numero, resultado) VALUES (13, 142, 9, 'Rz 1.2', 'Comunidades educativas de grupos étnicos y socioeconómicos diversos han construido puentes entre sí, fortaleciendo el reconocimiento del otro, la convivencia pacífica y la generación de confianzas, orientadas al restablecimiento de relaciones justas, el respeto a la diferencia y la equidad de género, desde el encuentro intergeneracional e interétnico');
          INSERT INTO cor1440_gen_resultadopf (id, proyectofinanciero_id, objetivopf_id, numero, resultado) VALUES (14, 142, 9, 'Rz 1.3', 'Conformada una Red de liderazgo socio-ambiental para la paz, que desarrolla acciones concretas para el cuidado de los Sistemas Socio-ecológicos como base fundamental para la consolidación de una cultura de paz en los territorios focalizados');
          
          SELECT setval('cor1440_gen_resultadopf_id_seq', MAX(id)+1, true) FROM cor1440_gen_resultadopf;
          
          
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (1, 142, 11, 'I.0.1', 'Se cuenta con una medición inicial de línea base que da cuenta del punto de partida para los indicadores del proyecto.', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (72, 142, NULL, 'OE.I.1', ' % de adolescentes y  jóvenes formados, actúan como promotores de paz en sus comunidades educativas y se articulan en red con otros para contribuir a la construcción de una cultura de paz y sostenibilidad.', NULL, 9);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (69, 142, NULL, 'OG.I1', 'Se ha aumentado el liderazgo para la disminución de conductas violentas y la consolidación de una cultura de paz desde las comunidades educativas en las regiones priorizadas.', NULL, 8);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (70, 142, NULL, 'OG.I2', 'Se han fortalecido habilidades sociales de los jóvenes, padres/madres, docentes  y  líderes/lideresas comunitarios para contribuir a la transición hacia un país reconciliado y en paz donde las relaciones justas y equitativas son un principio ético de toda la sociedad.', NULL, 8);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (71, 142, NULL, 'OG.I3', 'Los jóvenes e instituciones educativas focalizadas integran el enfoque de gobernanza y sostenibilidad ambiental como un eje fundamental en la consolidación de una cultura de paz desde la escuela.', NULL, 8);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (73, 142, NULL, 'OE.I.2', ' % de instituciones educativas que han integrado la cultura de paz como un eje central de sus planes educativos institucionales y lo implementan de forma práctica a través de la cátedra para la paz.', NULL, 9);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (74, 142, NULL, 'OE.I.3', 'as comunidades educativas han desarrollado estrategias que fortalecen la convivencia pacífica y aclimatan la reconciliación en sus territorios', NULL, 9);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (75, 142, NULL, 'OE.I.4', '% de instituciones educativas que implementan estrategias de responsabilidad socio-ecológica en sus proyectos escolares, desde un enfoque de gobernanza ambiental para la paz.', NULL, 9);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (77, 142, 11, 'I.0.2', 'Metodologías y herramientas compiladas, actualizadas, adaptadas y disponibles para la acción.', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (78, 142, 11, 'I.0.3', 'Mejora de un  23% en el ICO de la Organización Proterra, una vez implementado el plan de mejora.', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (79, 142, 11, 'I.0.4', 'Al cierre de la acción se cuenta con una evaluación externa que da cuenta de los cambios logrados', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (80, 142, 12, 'I.1.1', ' % de los adolescentes y jóvenes que aumentan su conocimiento, habilidades y actitudes favorables a la paz y actúan como promotores y mediadores de paz en sus centros educativos.', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (81, 142, 12, 'I.1.2', '%  de  jóvenes que participan en una de las redes asociadas al proyecto, divulgando y  liderando acciones de paz en sus comunidades de influencia.', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (82, 142, 12, 'I.1.3', '% de docentes formados que implementan prácticas pedagógicas orientadas a la transformación de violencia, mediación de conflictos y cultura de paz en el aula', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (83, 142, 12, 'I.1.4', '% de instituciones educativas que han iniciado el proceso de implementación de la cátedra para la paz ', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (84, 142, 12, 'I.1.5', ' % jóvenes, docentes y escuelas que utilizan la plataforma interactiva para su auto-formación, la difusión de sus acciones  y la articulación en red', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (85, 142, 13, 'I.2.1', '% de participantes que aumentan niveles de confianza respecto a grupos con antecedentes u orígenes diferentes a nivel cultural, social, económico o político.', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (86, 142, 13, 'I.2.2', ' % jóvenes, docentes, padres- madres de familia y líderes comunitarios que fortalecen el sentido de lo colectivo y lideran acciones con base en la pluralidad y la diversidad. ', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (87, 142, 13, 'I.2.3', ' % de comunidades educativas, familias y miembros de comunidades de influencia que reconocen el valor de la reconciliación y  lo llevan la práctica', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (88, 142, 14, 'I.3.1', ' % de jóvenes y adolescentes que fortalecen sus conocimientos y los ponen en práctica para el reconocimiento de problemáticas socio-ambientales y potencialidades territoriales.', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (89, 142, 14, 'I.3.2', '% de jóvenes participantes que generan e implementan propuestas de impacto socio-ambiental en las instituciones educativas y comunidades de influencia.', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (90, 142, 14, 'I.3.3', '% de propuestas que han sido implementadas por los adolescentes y jóvenes en las instituciones educativas y comunidades de influencia.', NULL, NULL);
          INSERT INTO cor1440_gen_indicadorpf (id, proyectofinanciero_id, resultadopf_id, numero, indicador, tipoindicador_id, objetivopf_id) VALUES (91, 142, 14, 'I.3.4', 'Una ción compilando la memoria ambiental de las tres regiones focalizadas para el proyecto.', NULL, NULL);
          
          SELECT setval('cor1440_gen_indicadorpf_id_seq', MAX(id)+1, true) FROM cor1440_gen_indicadorpf;
          
          
          INSERT INTO cor1440_gen_actividadtipo (id, nombre, observaciones, fechacreacion, fechadeshabilitacion, created_at, updated_at, listadoasistencia) VALUES (101, 'TALLER / ENCUENTRO', '', '2015-07-17', NULL, '2015-07-17 21:14:15.020975', '2016-02-26 15:43:27.768427', NULL);
          INSERT INTO cor1440_gen_actividadtipo (id, nombre, observaciones, fechacreacion, fechadeshabilitacion, created_at, updated_at, listadoasistencia) VALUES (108, 'SISTEMA DE INFORMACIÓN', 'POR EJEMPLO COMUNICACIONES E INCIDENCIA', '2016-03-07', NULL, '2016-03-07 22:55:47.240146', '2016-03-07 22:55:47.240146', NULL);
          INSERT INTO cor1440_gen_actividadtipo (id, nombre, observaciones, fechacreacion, fechadeshabilitacion, created_at, updated_at, listadoasistencia) VALUES (118, 'CARACTERIZACIÓN DE BENEFICIARIOS Y LEVANTAMIENTO DE LÍNEA DE BASE', 'Tanto personas individuales como organizaciones y comunidades.', '2018-11-27', NULL, '2018-11-27 14:42:25.436966', '2018-11-27 14:43:37.783112', true);
          INSERT INTO cor1440_gen_actividadtipo (id, nombre, observaciones, fechacreacion, fechadeshabilitacion, created_at, updated_at, listadoasistencia) VALUES (119, 'FORTALECIMIENTO INSTITUCIONAL DE LAS ORGANIZACIONES', 'Se utiliza para los proyectos de la Unión Europea donde se requiere levantar el Indice de capacidades de la organizaciones (ICO)', '2018-11-27', NULL, '2018-11-27 14:45:58.911628', '2018-11-27 14:47:19.372634', false);
          INSERT INTO cor1440_gen_actividadtipo (id, nombre, observaciones, fechacreacion, fechadeshabilitacion, created_at, updated_at, listadoasistencia) VALUES (120, 'DISEÑO, PLANEACIÓN Y CONSTRUCCIÓN DE METODOLOGIAS Y CONTENIDOS DE PROCESOS FORMATIVOS', 'Se utiliza par alas actividades de planificación, programación y diseño de metodologías para los procesos formativos, tanto formales cono no formales e informales.', '2018-11-27', NULL, '2018-11-27 14:52:01.969026', '2018-11-27 14:53:54.25232', false);
          INSERT INTO cor1440_gen_actividadtipo (id, nombre, observaciones, fechacreacion, fechadeshabilitacion, created_at, updated_at, listadoasistencia) VALUES (121, 'PROCESO FORMATIVO, FORMAL/NO FORMAL/INFORMAL', 'Implementación de los procesos formativos planeados para los proyectos, pueden ser formales tipos diplomado, o no formales e informales.', '2018-11-27', NULL, '2018-11-27 15:07:06.933677', '2018-11-27 15:09:42.895537', false);
          INSERT INTO cor1440_gen_actividadtipo (id, nombre, observaciones, fechacreacion, fechadeshabilitacion, created_at, updated_at, listadoasistencia) VALUES (122, 'ACOMPAÑAMIENTO A INSTITUCIONES EDUCATIVAS', 'Se utiliza cuando en el marco de un proyecto, se hacen asesorías a instituciones educativas de cualquier nivel.', '2018-11-27', NULL, '2018-11-27 15:16:10.583353', '2018-11-27 15:17:20.174451', false);
          INSERT INTO cor1440_gen_actividadtipo (id, nombre, observaciones, fechacreacion, fechadeshabilitacion, created_at, updated_at, listadoasistencia) VALUES (123, 'SEMINARIOS INTERNOS/ INTERCAMBIOS DE EXPERIENCIAS ORGANIZACIONALES', '', '2018-11-27', NULL, '2018-11-27 15:40:23.327668', '2018-11-27 15:40:59.689298', false);
          INSERT INTO cor1440_gen_actividadtipo (id, nombre, observaciones, fechacreacion, fechadeshabilitacion, created_at, updated_at, listadoasistencia) VALUES (124, 'RECOPILACIÓN DE HISTORIAS, RELATOS, ENTREVISTAS, NARRACIONES DE BENEFICIARIOS', '', '2018-11-27', NULL, '2018-11-27 15:41:26.283177', '2018-11-27 15:41:55.856199', false);
          INSERT INTO cor1440_gen_actividadtipo (id, nombre, observaciones, fechacreacion, fechadeshabilitacion, created_at, updated_at, listadoasistencia) VALUES (127, 'ASISTENCIA/SEGUIMIENTO TÉCNICO A INICIATIVAS DE LOS PARTICIPANTES', '', '2018-11-27', NULL, '2018-11-27 15:53:36.01819', '2018-11-27 15:53:57.851484', false);
          
          
          SELECT setval('cor1440_gen_actividadtipo_id_seq', MAX(id) + 1 , true) FROM cor1440_gen_actividadtipo;
          
          
          
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (199, 142, 'A.0.4', 'Diseño e implementación de Plan de monitoreo y seguimiento periódico. ', 'Diseño e implementación de Plan de monitoreo y seguimiento periódico al proyecto tejedores de vida. ', 11, 6);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (198, 142, 'A.0.3', 'Compilación del Canasto de conocimiento y el semillero de herramientas', 'Compilación de herramientas y metodologías y adaptación de estas a las necesidades de la acción y de los participantes.', 11, 120);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (28, 142, 'A.0.1', 'Levantamiento de Estudio de linea Base', 'Levantamiento de línea de base: Medición inicial de los indicadores. ', 11, 118);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (52, 142, 'A.0.2', 'Aplicación del ICO a Fundación Proterra y elaboración de plan de fortalecimiento', 'Aplicación del ICO a Fundación Proterra y elaboración de plan de fortalecimiento', 11, 119);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (200, 142, 'A.0.5', 'Evaluación externa', 'Evaluación externa para medir el impacto y la calidad de las acciones', 11, 6);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (201, 142, 'A 1.1.1', 'Proceso de formación en ciudadanías creativas para la paz ', 'Proceso de formación en ciudadanías creativas para la paz dirigida a 640 adolescentes y jóvenes estudiantes en dieciséis instituciones educativas públicas y privadas, para la promoción de una cultura de paz desde la escuela, que fortalezca el trabajo en red de los jóvenes.', 12, 121);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (206, 142, 'A 1.1.6', 'Creación de una plataforma tecnológica interactiva.', 'Creación de una herramienta tecnológica (plataforma interactiva) con tres componentes pertinentes a los fines del proyecto. En este resultado,  orientado a la difusión y apropiación  entre los jóvenes de contenidos, conceptos, dinámicas, experiencias y herramientas para la mediación creativa de conflictos y la promoción de cultura de paz.', 12, 108);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (202, 142, 'A 1.1.2', 'Proceso “del 9 al 9, quiéreme bien, herédame la paz” ', 'Desarrollo de una campaña anual de sensibilización y promoción de cultura de paz en las instituciones educativas y sus  comunidades de influencia a partir del proceso “del 9 al 9, quiéreme bien, herédame la paz” implementada por el SJR, Acodesi y otras organizaciones aliadas de la Compañía de Jesús.', 12, 17);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (203, 142, 'A 1.1.3', 'Curso de Formación/Diplomado “Ciudadanías creativas y ecología para la paz desde la escuela”', 'Curso de Formación/Diplomado para 96 educadores en “Ciudadanías creativas y ecología para la paz desde la escuela”, orientado al fortalecimiento de habilidades para abordar la paz y la reconciliación en el aula', 12, 121);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (204, 142, 'A 1.1.4', 'Orientación y Asesoría a las instituciones educativas en torno a la cátedra para la paz', 'Desarrollo de un plan de orientación y asesoría a las instituciones educativas para la implementación de la cátedra para la paz, fomentando el intercambio de experiencias entre escuelas', 12, 122);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (207, 142, 'A 1.2.1', 'Aplicación de las herramientas para la reconciliación desarrolladas por el JRS', 'A partir del contexto de cada región, aplicación de las herramientas para la reconciliación desarrolladas por el SJR, para la promoción de ejercicios de encuentro-reflexión-acción entre grupos de madres, padres y docentes, en al menos 5 de las instituciones educativas focalizadas.', 13, 101);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (208, 142, 'A 1.2.2', 'Encuentros Tejedores de Sociedad', 'Realización de encuentros Tejedores de Sociedad, a modo de semilleros de convivencia, entre grupos diversos a nivel generacional e interétnicos, que favorezcan relaciones de confianza, reconocimiento y equidad en 3 regiones del país.', 13, 101);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (209, 142, 'A 1.2.3', 'Recopilación de historias y experiencias de vida de “mujeres artesanas de vida y paz” ', 'Recopilación de historias y experiencias de vida de “mujeres artesanas de vida y paz” en los que se resalte el importante pero invisible papel que las mujeres juegan en la construcción de la paz en Colombia, aún a pesar de haber sido población altamente vulnerable 
          a la violencia y el conflicto armado
          ', 13, 124);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (210, 142, 'A 1.2.4', 'Seminario interno de formación', 'Realización de un seminario de formación al equipo del proyecto y de las instituciones asociadas para la apropiación de herramientas y conocimientos que fortalezcan sus capacidades para la promoción de la paz, la reconciliación y la gobernanza ambiental.', 13, 123);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (211, 142, 'A 1.3.1', 'Realización de Encuentros de reconstrucción de la memoria ambiental', '24 Encuentros de reconstrucción de la memoria ambiental en las tres regiones focalizadas en el proyecto, con la participación de las instituciones educativas y actores representativos de la comunidad, que permitan identificar los motores de cambio en los ecosistemas y los conflictos socio ambientales y favorezcan la apropiación y empoderamiento de los jóvenes sobre su territorio.', 14, 101);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (212, 142, 'A 1.3.2', 'Realización Campamentos de formación-Accion', 'Desarrollo de  tres campamentos de formación-acción con 120 jóvenes, adolescentes y 10 docentes de la Red de liderazgo socio-ambiental para la Paz, para el reconocimiento de las problemáticas y potencialidades del territorio y la generación de proyectos orientados a la armonización de las relaciones ser humano-naturaleza que aporten a la paz territorial.', 14, 101);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (214, 142, 'A 1.3.4', 'Realización encuentro nacional del nodo ambiental de la Red juvenil', 'Realización de un encuentro nacional del nodo ambiental de la Red juvenil de las instituciones educativas focalizadas para el intercambio de aprendizajes y la construcción de agendas de sostenibilidad ambiental para la paz en las comunidades educativas.', 14, 101);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (213, 142, 'A 1.3.3', 'Implementación de 25 proyectos Socio-Ambientales', 'Apoyo a la puesta en marcha de 25 proyectos ambientales liderados por grupos de jóvenes y que tengan impacto en entornos educativos y comunidades de influencia', 14, 127);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (215, 142, 'A 1.3.5', 'Desarrollo de una plataforma tecnológica interactiva con contenidos pertinentes a los fines del proyecto', 'Desarrollo de una plataforma tecnológica interactiva con contenidos pertinentes a los fines del proyecto. En este resultado, incluyendo informacion orientada a la democratización del conocimiento sobre ecología para la paz entre jóvenes, instituciones educativas y comunidades.', 14, 108);
          INSERT INTO cor1440_gen_actividadpf (id, proyectofinanciero_id, nombrecorto, titulo, descripcion, resultadopf_id, actividadtipo_id) VALUES (205, 142, 'A 1.1.5', 'Realización de encuentro, para intercambios de aprendizajes y experiencias.', 'Realización de un encuentro nacional entre las dieciséis escuelas participantes, para el intercambio de aprendizajes y la construcción de agendas de paz sostenible en las comunidades educativas.', 12, 101);
          SELECT setval('cor1440_gen_actividadpf_id_seq', MAX(id) + 1, true) FROM cor1440_gen_actividadpf;
        SQL
    end
  end
  def down
  end
end
